//User Actions
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

// Business Actions
export const ADD_BUSINESS = "ADD_BUSINESS";
export const EDIT_BUSINESS = "EDIT_BUSINESS";
export const DELETE_BUSINESS = "DELETE_BUSINESS";
export const VIEW_BUSINESS = "VIEW_BUSINESS";
export const GET_ALL_BUSINESS = "GET_ALL_BUSINESS";
export const SEARCH_FOR_BUSINESS = "SEARCH_FOR_BUSINESS";
export const LOADING_BUSINESSES = "LOADING_BUSINESSES";
export const GET_ONE_BUSINESS = "GET_ONE_BUSINESS";

// Review Actions
export const ADD_REVIEW = "ADD_REVIEW";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";

// Connection Reducers
export const NOFITY_NO_INTERCONNECTION = "NOFITY_NO_INTERCONNECTION"
export const TOGGLE_CONNECTION_TOKEN_STATE = "TOGGLE_CONNECTION_TOKEN_STATE";