//User Actions
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_LOGIN_MESSAGES = "CLEAR_LOGIN_MESSAGES";
export const CLEAR_SIGNUP_MESSAGES = "CLEAR_SIGNUP_MESSAGES";
export const CLEAR_LOGOUT_MESSAGES = "CLEAR_LOGOUT_MESSAGES";
export const RESET_PASSWORD = "RESET_PASSWORD";

// Business Actions
export const ADD_BUSINESS = "ADD_BUSINESS";
export const EDIT_BUSINESS = "EDIT_BUSINESS";
export const DELETE_BUSINESS = "DELETE_BUSINESS";
export const VIEW_BUSINESS = "VIEW_BUSINESS";
export const GET_ALL_BUSINESS = "GET_ALL_BUSINESS";
export const SEARCH_FOR_BUSINESS = "SEARCH_FOR_BUSINESS";
export const LOADING_BUSINESSES = "LOADING_BUSINESSES";
export const GET_ONE_BUSINESS = "GET_ONE_BUSINESS";
export const CLEAR_DELETE_MESSAGE = "CLEAR_DELETE_MESSAGE";
export const CLEAR_EDIT_MESSAGE = "CLEAR_EDIT_MESSAGE";
export const CLEAR_NEW_BUSINESS_MESSAGE = "CLEAR_NEW_BUSINESS_MESSAGE";

// Review Actions
export const ADD_REVIEW = "ADD_REVIEW";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const CLEAR_REVIEW_LIST = "CLEAR_REVIEW_LIST";
export const CLEAR_NEW_REVIEW_MESSAGE = "CLEAR_NEW_REVIEW_MESSAGE";

// Connection Actions
export const START_FETCHING_DATA = "START_FETCHING_DATA";
export const STOP_FETCHING_DATA = "STOP_FETCHING_DATA";
export const NOFITY_NO_INTERCONNECTION = "NOFITY_NO_INTERCONNECTION"
export const TOGGLE_CONNECTION_TOKEN_STATE = "TOGGLE_CONNECTION_TOKEN_STATE";